/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BoilerplateRouteImport } from './routes/boilerplate'
import { Route as UsersRouteImport } from './routes/Users'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CPageIdRouteImport } from './routes/c/$pageId'
import { Route as loginLoginRouteImport } from './routes/(login)/login'
import { Route as dashboardDashboardRouteImport } from './routes/(dashboard)/dashboard'

const BoilerplateRoute = BoilerplateRouteImport.update({
  id: '/boilerplate',
  path: '/boilerplate',
  getParentRoute: () => rootRouteImport,
} as any)
const UsersRoute = UsersRouteImport.update({
  id: '/Users',
  path: '/Users',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CPageIdRoute = CPageIdRouteImport.update({
  id: '/c/$pageId',
  path: '/c/$pageId',
  getParentRoute: () => rootRouteImport,
} as any)
const loginLoginRoute = loginLoginRouteImport.update({
  id: '/(login)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const dashboardDashboardRoute = dashboardDashboardRouteImport.update({
  id: '/(dashboard)/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Users': typeof UsersRoute
  '/boilerplate': typeof BoilerplateRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/login': typeof loginLoginRoute
  '/c/$pageId': typeof CPageIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Users': typeof UsersRoute
  '/boilerplate': typeof BoilerplateRoute
  '/dashboard': typeof dashboardDashboardRoute
  '/login': typeof loginLoginRoute
  '/c/$pageId': typeof CPageIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Users': typeof UsersRoute
  '/boilerplate': typeof BoilerplateRoute
  '/(dashboard)/dashboard': typeof dashboardDashboardRoute
  '/(login)/login': typeof loginLoginRoute
  '/c/$pageId': typeof CPageIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Users'
    | '/boilerplate'
    | '/dashboard'
    | '/login'
    | '/c/$pageId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Users' | '/boilerplate' | '/dashboard' | '/login' | '/c/$pageId'
  id:
    | '__root__'
    | '/'
    | '/Users'
    | '/boilerplate'
    | '/(dashboard)/dashboard'
    | '/(login)/login'
    | '/c/$pageId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsersRoute: typeof UsersRoute
  BoilerplateRoute: typeof BoilerplateRoute
  dashboardDashboardRoute: typeof dashboardDashboardRoute
  loginLoginRoute: typeof loginLoginRoute
  CPageIdRoute: typeof CPageIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/boilerplate': {
      id: '/boilerplate'
      path: '/boilerplate'
      fullPath: '/boilerplate'
      preLoaderRoute: typeof BoilerplateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Users': {
      id: '/Users'
      path: '/Users'
      fullPath: '/Users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/c/$pageId': {
      id: '/c/$pageId'
      path: '/c/$pageId'
      fullPath: '/c/$pageId'
      preLoaderRoute: typeof CPageIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(login)/login': {
      id: '/(login)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(dashboard)/dashboard': {
      id: '/(dashboard)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsersRoute: UsersRoute,
  BoilerplateRoute: BoilerplateRoute,
  dashboardDashboardRoute: dashboardDashboardRoute,
  loginLoginRoute: loginLoginRoute,
  CPageIdRoute: CPageIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
